services:
  web:
    build:
      context: .
      dockerfile: apache2.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
    # depends_on:
    #   - db

  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: exampledb
  #     MYSQL_USER: exampleuser
  #     MYSQL_PASSWORD: examplepassword
    # ports:
    #   - "3306:3306"
